# Generated by Django 3.2.25 on 2026-05-06 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('author', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('fiction', 'Fiction'), ('history', 'History'), ('science', 'Science')], default='fiction', max_length=20)),
            ],
        ),
    ]
