# Generated by Django 3.2.25 on 2026-05-06 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20260506_1910'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='category',
            new_name='genre',
        ),
        migrations.RemoveField(
            model_name='book',
            name='quantity',
        ),
    ]
