# Generated by Django 6.0.5 on 2026-05-15 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_book_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(default='undefined', max_length=100),
        ),
    ]
